### ISSUE TITLE
[3.5.0] This release of Retype has expired. Please update to the latest release. A Retype license is required to continue using this release.

### ISSUE THREAD

**Issue by saydeicide** [retypeapp/retype#708]
after server reatert, i cannot start retype.

$ retype start -n --host 192.168.0.37 --pro
  INPUT: /engine/retype
 OUTPUT: [in-memory]
ERROR: This release of Retype has expired. Please update to the latest release. A Retype license is required to continue using this release.

i use free version.

## See also

- #712

**Comment by cclypeatus** [comment]
Facing the same issue. Today happens to be the anniversary of v3.5.0, so could it be that the free version gets a year-long license that renews on every release?

**Comment by chrstn-opntdc** [comment]
We are encountering the same issue and have a pro license valid until 2027

**Comment by altworkz** [comment]
This is also encountered in our setup (Retype Pro v3.5.0).

**Comment by geoffreymcgill** [comment]
I am investigating.

**Comment by mduft** [comment]
Same issue here :)

**Comment by ansel-nekuti** [comment]
Same issue here. We're using the free version.

**Comment by clabeuhtegrite** [comment]
Same issue here. I use the free version.

**Comment by abergdesign** [comment]
Same for us, Ubuntu 24.04, retype 3.5.0 free version

**Comment by kbudde** [comment]
Affects also the licensed version, just saying 💥

**Comment by zakaria-chahboun** [comment]
Same here

**Comment by kcowgill** [comment]
Watching. Adding that indeed the licensed version is also affected. The error messaging is slightly different:

```
❯ retype start --host REDACTED
  INPUT: /Users/kcowgill/docs
 OUTPUT: [in-memory]
ERROR: Failed to access the wallet. This release of Retype has expired. Please update to the latest release. A Retype license is required to continue using this release.
       Please use the "--clear" option to reset the wallet if the problem persists.
```

I went ahead and cleared the wallet and attempted to re-add our key:

```
❯ retype wallet --add REDACTED
ERROR: Failed to save the wallet. This release of Retype has expired. Please update to the latest release. A Retype license is required to continue using this release.
ERROR:
         - Status:                       Valid
         - Expires:                      2025-05-15 11:34
         - Max pages:                    1000000
```

**Comment by alec-drw** [comment]
+1

**Comment by kcowgill** [comment]
> I am investigating.

@geoffreymcgill Any updates?

**Comment by geoffreymcgill** [comment]
The fix is in place, but just trying to correct a couple issues with the release/deployment process, then v3.6.0 will be released. I'm working on it right now and will release v3.6.0 immediately after all green on the build.

**Comment by geoffreymcgill** [comment]
Retype v3.6.0 has been released. 

If you are using the GitHub [Action](https://retype.com/guides/github-actions/) using the `@latest` tags, your project will automatically pickup and build with the v3.6.0 release upon your next commit to your repo. Just commit a change and your website will build with v3.6.0.

If you are building with Retype on your local machine, updating to the latest release is required, see:

https://retype.com/guides/getting-started/#update

If for some reason running the `update` command does not actually update your local release, [uninstall](https://retype.com/guides/getting-started/#uninstall) Retype, then [install](https://retype.com/guides/getting-started/#install):

```
npm uninstall retypeapp --global
npm install retypeapp --global
```

The Docker containers have not been updated. There is still a small issue with our deployment process that needs to get worked out. This will be the next thing to fix and then I'll make a `3.6.1` release.

Once I'm caught up and everything is stabilized, I'll provide an update and explanation on what happened, plus how this issue will not happen in the future. 

I truly apologize the inconvenience this has caused for everyone.

Please let me know if you run into any issues and I will do my best to assist.

**Comment by latenitefilms** [comment]
I'm still seeing this on v3.6.0? Maybe my license has expired?

<img width="752" alt="image" src="https://github.com/user-attachments/assets/9c8439b0-07ab-4278-b025-25d367a83e73">

**Comment by geoffreymcgill** [comment]
> I'm still seeing this on v3.6.0? Maybe my license has expired?

Hi @latenitefilms. Basically, yes, your key has expired. I will explain below, but if you send me an email to hello@retype.com, I will help get you back online immediately.

Here is the explanation of what's happening...

If you have the license key installed locally, you can run the command `retype wallet --list`, which will list out all the license keys you have installed. When I test one of your license keys, I see the following:

```
- Free upgrades until:          2024-05-25 17:39
```

The Retype license keys technically do not expire. What expires is the window for which _free upgrades_ are available. 

Your license key was valid for free upgrades until May 25, 2024.

The previous release of Retype (v3.5.0) was released on Sep 16, 2023. Your key would work for any new releases up to May 5, 2024.

With the release of v3.6.0 on Sep 17, 2024, your Retype Pro license key is no longer available for that free upgrade. 

We need to improve the message that is output when that `Free upgrades until:` date occurs. Sorry about that.

**Comment by geoffreymcgill** [comment]
> The `retype --version` output includes a SHA appended to the version number, causing the latest GitHub Action to fail the [built-in version check](https://github.com/retypeapp/action-build/blob/main/build.sh#L38).

Confirmed, I noticed this as well. I am investigating right now.

**Comment by latenitefilms** [comment]
I was under the impression we got three years of updates?

https://retype.com/pro/

Has it been three years already?!?

I was also under the impression that if your license expired, it just rolls back to the free version based on this:

https://retype.com/pro/#if-i-do-not-renew-does-my-website-stop-working

**Comment by latenitefilms** [comment]
Any news @geoffreymcgill ?

I got your first email, but haven't received any new license keys yet?

I'd love to get this solved ASAP, as I'm using Retype for a news site (FCP Cafe), so it's a bit of a bummer I can't update the site.

**Comment by wtrucci** [comment]
> Retype v3.6.0 has been released.
> 
> If you are using the GitHub [Action](https://retype.com/guides/github-actions/) using the `@latest` tags, your project will automatically pickup and build with the v3.6.0 release upon your next commit to your repo. Just commit a change and your website will build with v3.6.0.
> 
> If you are building with Retype on your local machine, updating to the latest release is required, see:
> 
> https://retype.com/guides/getting-started/#update
> 
> If for some reason running the `update` command does not actually update your local release, [uninstall](https://retype.com/guides/getting-started/#uninstall) Retype, then [install](https://retype.com/guides/getting-started/#install):
> 
> ```
> npm uninstall retypeapp --global
> npm install retypeapp --global
> ```
> 
> The Docker containers have not been updated. There is still a small issue with our deployment process that needs to get worked out. This will be the next thing to fix and then I'll make a `3.6.1` release.
> 
> Once I'm caught up and everything is stabilized, I'll provide an update and explanation on what happened, plus how this issue will not happen in the future.
> 
> I truly apologize the inconvenience this has caused for everyone.
> 
> Please let me know if you run into any issues and I will do my best to assist.

Hi, any news on docker image?

**Comment by maurxce** [comment]
Experiencing the same issue, my wiki is not useable anymore due to this.
I deployed it via docker, is there some temporary fix for now?

**Comment by latenitefilms** [comment]
In my case, @geoffreymcgill sent me new license keys which did the trick.

**Comment by leadenhall** [comment]
> The `retype --version` output includes a SHA appended to the version number, causing the latest GitHub Action to fail the [built-in version check](https://github.com/retypeapp/action-build/blob/main/build.sh#L38).
> 
> ```
> $ retype --version
> 3.6.0+6fe53cf630452bb1c91973116e3a4af3297f2556
> ```

We are still not able to use the GHA workflow due to this issue. Any updates on that front?

**Comment by JoelMTaylor** [comment]
@geoffreymcgill, I have the same issue as latenitefilms. I have sent emails to hello@retype.com, but I haven't received a reply.

**Comment by SinsinwarHunk** [comment]
> Docker containers have not been updated.

any update for Docker images, getting "ERROR: This release of Retype has expired. Please update to the latest release. A Retype license is required to continue using this release."

**Comment by latenitefilms** [comment]
@geoffreymcgill - I'm having some issues with some of my other sites too now. I've sent an email. Hopefully it hasn't ended up in your spam filter. Thanks mate!

**Comment by latenitefilms** [comment]
Here's my build that's currently failing:

https://github.com/CommandPost/CommandPost-Website/actions/runs/11944698551/job/33296100804

**Comment by latenitefilms** [comment]
For anyone following along, I was able to get it all working again with this:

```
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - uses: retypeapp/action-build@a95ca1f9508dec8465a93f2e50a1228d22e90f4e
        with:
          license: ${{ secrets.RETYPE_SECRET }}

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
```

...basically just using an older version of Retype.

**Comment by scottsemple** [comment]
I had the same issue. After updating to 3.6.0, I deleted my local repo and re-cloned the remote. Seems to be working now.

**Comment by tsoderling** [comment]
I see others have ran into this problem as well using the latest release of the GitHub Action "retypeapp/action-build":

`Error: Found existing installation of retype for a different version than this action is intended to work with.
Expected version: 3.6.0
Available version: 3.6.0+6fe53cf630452bb1c91973116e3a4af3297f2556`

Was this ever resolved?

**Comment by PeterBurner** [comment]
@geoffreymcgill could you please update the official docker image to 3.6.0 ?

**Comment by geoffreymcgill** [comment]
This issue has been fixed. Please upgrade to the latest release of Retype. Closing this issue for now, but will reopen if there is a fresh report of errors still occurring.
